apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    microclimate-release: {{ .Values.microclimate.release.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
        microclimate-release: {{ .Values.microclimate.release.name }}
    spec:
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          volumeMounts: 
          - name: shared-workspace
            mountPath: /microclimate-workspace/
            subPath: {{ .Values.user.name }}
          env:
            - name: PROJECT_NAME
              value: {{ .Values.project.name }}
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "/root/artifacts/init_liberty_pod.sh"]
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      volumes: 
      - name: shared-workspace
        persistentVolumeClaim:
          claimName: {{ .Values.volume.pvc.name }}