# Default values for idc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: <idc-repo>
  tag: latest
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
  volumes:
    name:
service:
  name: node
  type: NodePort
  internalPort: 9080